# Generated by Django 5.0.7 on 2024-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="suggested_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=7, null=True
            ),
        ),
    ]
