# Generated by Django 5.0.7 on 2024-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_product_release_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="id",
        ),
    ]
